Fix for retrive session in sync and async both
meta-llama/llama-stack-client-python pull request #7
Opened 2024-10-24 07:49 UTC by cheesecake100201

This error is occuring because, in the main implementation of this API endpoint, its a post request (Even though it should be a GET request) and agent_id and session_id are being passed in the body where as this method is sending it in query_params which is causing a 400 Error and a pydantic error of FASTAPI. This is a fix for now but might suggest converting fetching methods in implementation to be converted into GET methods in llama stack repo.

2024-10-25 00:47 UTC, yanxi0830 requested changes
The client SDK is auto-generated based on OpenAPI spec. This should be fixed with the server webmethod endpoint and [OpenAPI spec](https://github.com/meta-llama/llama-stack/blob/main/docs/resources/llama-stack-spec.yaml) instead.

2024-10-25 05:17 UTC, cheesecake100201 commented
> The client SDK is auto-generated based on OpenAPI spec. This should be fixed with the server webmethod endpoint and [OpenAPI spec](https://github.com/meta-llama/llama-stack/blob/main/docs/resources/llama-stack-spec.yaml) instead. 

So do you mean I should change the implementation on the server side in the llama stack report
@yanxi0830

2024-10-25 16:26 UTC, yanxi0830 commented
@cheesecake100201 Yes, I think we should make sure (1) server side is also implemented as GET (2) OpenAPI spec is a GET (3) client SDK is a GET.

2025-03-07 19:30 UTC, yanxi0830 commented
Closing as this is no longer relevant.

2025-03-07 19:30 UTC, closed without merging